### ISSUE TITLE
Manifest needs version

### ISSUE THREAD

**Issue by Mod74** [i-am-shodan/HomeAssistantUnifiDirect#1]
Noticed this is my log after installing

`ERROR (SyncWorker_1) [homeassistant.loader] The custom integration 'unifi_direct' does not have a version key in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details`

manually added it, but adding to repo might be useful :) Thanks.

**Comment by i-am-shodan** [comment]
Thanks, I had forgotten to push up my working changes
